### ISSUE TITLE
Feature request: Add the new failed requests stats to the HTML output

### ISSUE THREAD

**Issue by Lamera** [benc-uk/k6-reporter#15]
# Feature request
## Part 1
K6 added a new default metric in [v0.31.0](https://github.com/loadimpact/k6/releases/tag/v0.31.0) called "http_req_failed". It would be great to have that stats also in the HTML summary.
![grafik](https://user-images.githubusercontent.com/19840658/111294158-519ede00-864a-11eb-985c-05fb48f18a8e.png)
## Part 2 (Question)
Is there an easy way to include the URLs with its status in the HTML output? When I run K6 tests and some requests fail, I probably want to know what the URLs are. Of course, I can always create a CSV file to get that info. But it would be more convenient to have this information directly in the same window.

**Comment by benc-uk** [comment]
Part 1 - good idea, I've added it to v2.2.0 released just now
Part 2 - Sorry this isn't possible, as k6 doesn't make this sort of information available to the summary data, only in the full data output (like CSV as you mention)
