### ISSUE TITLE
groups and tags

### ISSUE THREAD

**Issue by emil45** [benc-uk/k6-reporter#17]
I'm trying to group two requests (though it will give me duration for each request - k6 sum it to group duration :()

But anyway, I'm not sure if this error coming from `k6-reporter`:
```
INFO[0028] [k6-reporter v2.2.0] Generating HTML summary report  source=console
ERRO[0028] handleSummary() failed with error "TypeError: Cannot read property 'passes' of undefined", falling back to the default summary  source=console
```

(and if you have any idea of how to separate two requests to two different metrics of `http_req_duration`... and it will look good on the html ... I will be more than thankful)

**Comment by benc-uk** [comment]
I don't think there's anyway to separate the metrics for different requests in the k6 summary data, it's doesn't provide that level of data, only the k6 output data stream has this

As for your error, which version of k6 are you using? (run `k6 version` to check), please try again using version 0.31.0

**Comment by emil45** [comment]
v0.31.0 - but you can close, i left the groups and stage - moved to scenarios ...

**Comment by emil45** [comment]
v0.31.0 - but you can close, i left the groups and stage - moved to scenarios ...
