### ISSUE TITLE
Cannot read property 'values' of undefined"

### ISSUE THREAD

**Issue by emil45** [benc-uk/k6-reporter#19]
Hi Ben,

New error popped - never saw it before:

```
ERRO[0003] handleSummary() failed with error "TypeError: ejs:301
    299|             <h4>Virtual Users</h4>
    300|             <i class="fas fa-user icon"></i>
 >> 301|             <div class="row"><div>Min</div><div><%= data.metrics.vus.values.min %></div></div>
    302|             <div class="row"><div>Max</div><div><%= data.metrics.vus.values.max %></div></div>
    303|           </div>
    304|         </div>

Cannot read property 'values' of undefined", falling back to the default summary  source=console
```

I don't have a clue why ... because other test suites with `setup` and `teardown` functions - the `htmlSummary` working great.

**Comment by emil45** [comment]
Maybe something with the options ? but the same options works in other tests:

```
export const globalOptions = {
  setupTimeout: "5m",
  scenarios: {
    default: {
      executor: "per-vu-iterations",
      vus: 1,
      iterations: 1,
      maxDuration: "1h",
    },
  },
  thresholds: {
    "http_req_duration{scenario:default}": [`max>=0`],
    "http_req_sending{scenario:default}": [`max>=0`],
    "http_req_waiting{scenario:default}": [`max>=0`],
    "http_req_receiving{scenario:default}": [`max>=0`],
  },
  summaryTrendStats: ["min", "avg", "max", "p(90)", "p(95)"],
};
```

**Comment by ebarped** [comment]
Hi!

I was having the same error, and fixed it by adding a `sleep(1);` after each check.
Mi guess is that there is a race condition if you dont sleep, but im not sure.

I hope this helps you :)

**Comment by emil45** [comment]
Hi, I had already a sleep of 0.1, but changing to sleep(1) worked for some reason...
guess its something that can be fixed in the source code.

**Comment by chetan018** [comment]
Hi,I am using 5 vus and 1 iteration ,when using sleep(1) it is working fine but average response duration increases by 1 sec like 1.54 sec but when using i am using without sleep html report error but response duration is in ms.can you please help in attaining response duration in millisecond with html report working or is there any alternative to skip sleep and get response without sleep time.Thanks.
