### ISSUE TITLE
Publish this extension to npmjs

### ISSUE THREAD

**Issue by BePo65** [benc-uk/k6-reporter#23]
By now in the test file we have to import this extension via a path to github.

Wouldn't it be easier to import it from node_modules (after 'installing' it from npmjs) - at least when k6 is used in javascript / node based environments?

AFAIK for this all what is needed is a package.json with a 'main' property in the dist folder.

**Comment by BePo65** [comment]
k6 cannot use "local" modules. Sorry; should have tried it before.

**Comment by benc-uk** [comment]
I didn't think you could, otherwise that would have been my first choice! 😁
