### ISSUE TITLE
How to support the code with TypeScript

### ISSUE THREAD

**Issue by xyngfei** [benc-uk/k6-reporter#26]
any suggestion on how to overcome the issue when I import the htmlReport into TS?

![image](https://user-images.githubusercontent.com/17619539/117234376-726bfe80-ae57-11eb-9973-2a42650e1f84.png)

**Comment by benc-uk** [comment]
I think this is just VS Code not understanding importing from a URL, I don't think I have any control over this

**Comment by brion-fuller** [comment]
Maybe it would help to publish to npm.

**Comment by benc-uk** [comment]
k6 can't import from NPM or use node_modules

https://k6.io/docs/using-k6/modules/#bundling-node-modules

**Comment by brion-fuller** [comment]
Not natively but why not give the ability to bundle it?

**Comment by xyngfei** [comment]
yeah, k6 currently is supporting type definition.

**Comment by celluj34** [comment]
> k6 can't import from NPM or use node_modules
> 
> https://k6.io/docs/using-k6/modules/#bundling-node-modules

k6 can't import from npm, true, but when you build your code, it'll include everything you've imported, so k6 won't have to. I'd like to see an npm package for this as I don't like importing packages from arbitrary urls.
