### ISSUE TITLE
Use k6-reporter locally

### ISSUE THREAD

**Issue by trihm** [benc-uk/k6-reporter#31]
Hi, I really love to use this project on my local server because it's nice and really easy to read the report. But due to network connectivity, I can't reach github server. Any idea how to build it locally to use without a network connection?

Thank you guys for help !!

**Comment by benc-uk** [comment]
I think you should be able to download the bundle.js from https://github.com/benc-uk/k6-reporter/tree/main/dist place it alongside your tests and reference the local file path on the import

I've not tried it, but I believe it should work

**Comment by trihm** [comment]
Wow, it's worked, tks a lot! This project is cool, I can't imagine how I could make a report without it. Thank again for your answer and for such a great work
