### ISSUE TITLE
Report do not include Count metrics

### ISSUE THREAD

**Issue by apotrebin** [benc-uk/k6-reporter#32]
> I've following script where I use Counter metrics and I see it in standard output , but there is no such results in report

`import http from 'k6/http'
import { check, group } from 'k6'
import { Counter } from 'k6/metrics';
import { randomIntBetween } from 'https://jslib.k6.io/k6-utils/1.1.0/index.js';
import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";

export let options = {

    thresholds: {
      http_req_failed: ['rate == 0.00'],                                    
      http_req_duration: ["p(95)<10000", "p(90)<10000", "avg<10000"],
      http_reqs: ["count > 0"],
      'RESPONSE_STATUS_200': ['count > 0'],
      'DUPLICATES_COUNTER':  ['count < 10'],
      'RESPONSE_STATUS_500': ['count < 1'],
      'UNKNOWN_ERRORS':      ['count < 1']
    },
   
    duration: '2m',
    vus: 100,
    summaryTimeUnit: 'ms'
}

const duplicatesCounter = new Counter('DUPLICATES_COUNTER')
const responseStatus200 = new Counter('RESPONSE_STATUS_200')
const responseStatus500 = new Counter('RESPONSE_STATUS_500')
const unknownErrors = new Counter('UNKNOWN_ERRORS')

export default function () {
    const context = {
      headers: {'header1':'test'}}
    
    const productId = 1
    const merchant_id = randomIntBetween(60000, 70000) 

    const data = {"description": "load-test"}
   
    const res = http.post(`https://my-tests.api`, JSON.stringify(data), context)
    
    if(res.status === 200){
        if(res.json()['status'] !== 'error'){
            responseStatus200.add(1)
        } else if (res.json()['error']['message'].includes("уже был создан")) {
            duplicatesCounter.add(1)
        }
    }

    if(res.status === 500){
        responseStatus500.add(1)
        console.log(`"*** WARNING 500 ***\n" + "Status code: ${res.status}" + "\n" + ${JSON.stringify(res.body)}`)
    }

    if(res.status != 200 && res.status !=500 && res.json()['status'] !== 'error') {
        unknownErrors.add(1)
        console.log(`"*** WARNING unknown *** \n" + "Status code: ${res.status}" + "\n" + ${JSON.stringify(res.body)}`)
    }

    check(res, {'Create payment resposnse status text is "ok"': (res) => res.json()["status"] === 'ok',},) 

}

export function handleSummary(data) {
    return {
      "summary.html": htmlReport(data),
    }
  }`
  

  
<img width="1760" alt="k6" src="https://user-images.githubusercontent.com/7914938/145989950-c6307d80-e889-48a6-a193-d9160f3b3c75.png">

**Comment by PatrickLevy** [comment]
This pr adds support for count and rate values, as well as websockets: https://github.com/benc-uk/k6-reporter/pull/39

**Comment by benc-uk** [comment]
Fixed by #39
