### ISSUE TITLE
Can't find the html report inside docker

### ISSUE THREAD

**Issue by lgjsherond** [benc-uk/k6-reporter#38]
Running a test on docker and set the volume to /src on docker. After execution we can see the standard out saying generating report. But can't find the file . 

Guide me.

**Comment by cbo44** [comment]
@lgjsherond : can you provide information to reproduce ? code, docker command and output, version, ...

**Comment by lgjsherond** [comment]
We are running this test on CodeBuild.  The docker command. 
docker run -e "HTTPS_PROXY=http://localhost:3128" -v ${CODEBUILD_SRC_DIR}/src:/src -i loadimpact/k6 run --out influxdb=http://grafana:8086/grafana  /src/tests/app/index.js

The source code is. 
![image](https://user-images.githubusercontent.com/50234665/156919722-e58c220a-5005-4b2c-ad66-476b15dec24e.png)

we use ls -lR command to check the directory after execution. we can see the source files but not finding the summary.html file.

**Comment by lgjsherond** [comment]
the default path of the html report on docker was /home/k6/
