### ISSUE TITLE
Consider using handleSummary() function for HTML generation

### ISSUE THREAD

**Issue by sniku** [benc-uk/k6-reporter#4]
k6 v0.30.0 introduced a [handleSummary()](https://github.com/loadimpact/k6/releases/tag/v0.30.0) callback function that can generate HTML report at the end of the test.

Perhaps it would be nicer to implement the HTML report this way and then host it on https://jslib.k6.io/ ?

**Comment by benc-uk** [comment]
DONE!
This worked pretty well, a tiny bit of overhead on extra code added to the test, but that's offset by removing the whole "out of band" conversion process 

I've refactored the repo based on this approach
