### ISSUE TITLE
Is it possible to save html report by name <<scriptname>>.html instead of summary.html everytime?

### ISSUE THREAD

**Issue by monishcorreia** [benc-uk/k6-reporter#46]
Currently the html report gets saved by "summary.html" name. 

Is it possible to save it like <<scriptname>>.html

E.g. I have K6 scripts like GetAllUsers.js and CreateNewUser.js
So I want to save their html reports as GetAllUsers.html and CreateNewUser.html

Is it possible?

**Comment by benc-uk** [comment]
The docs have an example of naming the output, by providing your own handleSummary callback 

https://github.com/benc-uk/k6-reporter#multiple-outputs

e.g.

```js
export function handleSummary(data) {
  return {
    "my-name-here.html": htmlReport(data),
  };
}
```

**Comment by jimicze** [comment]
@benc-uk  This is not a dynamic option. Its not solving the problem.

**Comment by benc-uk** [comment]
Would this work?

```js
export function handleSummary(data) {
  reportRes = {};
  reportRes[someDynamicVar] = htmlReport(data)
  return reportRes;
}
```

(I've not had a chance to try it)
