### ISSUE TITLE
Error on running k6 report

### ISSUE THREAD

**Issue by jorgellimoz** [benc-uk/k6-reporter#47]
Hi, I'm trying to run some tests with k6 and generate a report on k6-reporter but I'm not able to do it. I get this error message.
<img width="1681" alt="error" src="https://user-images.githubusercontent.com/99482267/217330473-0b46d9c5-14ff-4805-851b-8dda59bac2e9.png">

**Comment by benc-uk** [comment]
This error has nothing to do with this library or package
Looks like your machine can't connect to the internet.

**Comment by jorgellimoz** [comment]
I'm connected to the internet. Can you tell me how can I solve this issue? Because I don't know what am I doing wrong.

**Comment by jorgellimoz** [comment]
> This error has nothing to do with this library or package Looks like your machine can't connect to the internet.

Thank you for your help. Now is working. It is because of the country I'm right now. But I've fixed the issue with a VPN.
