### ISSUE TITLE
how to make "result.html" dinamic?

### ISSUE THREAD

**Issue by ardikun1412** [benc-uk/k6-reporter#50]
i was try
```js
export function getNameOnly() {
  const path = require('path');
  const parsedPath = path.parse(__filename);
  const fileNameWithoutExt = parsedPath.name;
  return fileNameWithoutExt;
}

export function handleSummary(data) {
  const getName = getNameOnly();
  return {
    [`${getName}.html`]: htmlReport(data),
  };
}
```
but its not working,
ERRO[0002] handleSummary() failed with error "TypeError: Value is not an object: undefined", falling back to the default summary  source=console

**Comment by gequise** [comment]
@ardikun1412 

You can try with the following code:

`export function handleSummary(data, fileName) {
  return {
    [`${fileName}.html`]: htmlReport(data),
  };
}
`

Then, when calling the handleSummary function, provide the file name as an argument:

const fileName = 'filename_without_extension';
const summary = handleSummary(data, fileName);
`
