### ISSUE TITLE
Empty report generation error

### ISSUE THREAD

**Issue by xShuden** [benc-uk/k6-reporter#6]
I am getting an error while installing the Packr2 package. I could not find how to install the package. Missing Packr and Packr2 packages causes reports to be generated empty.

Console Logs:

`
$go get -u github.com/gobuffalo/packr/v2/packr2

> go: downloading github.com/gobuffalo/packr/v2 v2.8.1
> go: found github.com/gobuffalo/packr/v2/packr2 in github.com/gobuffalo/packr/v2 v2.8.1
> go: downloading github.com/spf13/cobra v1.1.3
> go: downloading golang.org/x/tools v0.1.0
> go: downloading github.com/karrick/godirwalk v1.16.1
> go: downloading golang.org/x/sync v0.0.0-20201207232520-09787c993a3a
> go: downloading github.com/gobuffalo/logger v1.0.3
> go: downloading github.com/sirupsen/logrus v1.8.0
> go: downloading github.com/markbates/errx v1.1.0
> go: downloading github.com/markbates/oncer v1.0.0
> go: downloading github.com/markbates/safe v1.0.1
> go: downloading github.com/inconshreveable/mousetrap v1.0.0
> go: downloading github.com/spf13/pflag v1.0.5
> go: downloading golang.org/x/crypto v0.0.0-20210218145215-b8e89b74b9df
> go: downloading github.com/magefile/mage v1.11.0
> go: downloading golang.org/x/sys v0.0.0-20210218155724-8ebf48af031b
> go: downloading golang.org/x/term v0.0.0-20201210144234-2321bbc49cbf
> go: golang.org/x/tools upgrade => v0.1.0
> go: golang.org/x/sync upgrade => v0.0.0-20201207232520-09787c993a3a
> go: golang.org/x/sys upgrade => v0.0.0-20210218155724-8ebf48af031b
> go: github.com/sirupsen/logrus upgrade => v1.8.0
> go: github.com/rogpeppe/go-internal upgrade => v1.7.0
> go: github.com/spf13/cobra upgrade => v1.1.3
> go: github.com/magefile/mage upgrade => v1.11.0
> go: golang.org/x/crypto upgrade => v0.0.0-20210218145215-b8e89b74b9df
> go: golang.org/x/term upgrade => v0.0.0-20201210144234-2321bbc49cbf
> go: github.com/gobuffalo/packd upgrade => v1.0.0
> go: github.com/gobuffalo/logger upgrade => v1.0.3
> go: github.com/spf13/pflag upgrade => v1.0.5
> go: github.com/karrick/godirwalk upgrade => v1.16.1

$./scripts/build.sh 

> **./scripts/build.sh: line 3: packr2: command not found**
> go: downloading github.com/Masterminds/sprig/v3 v3.2.0
> go: downloading github.com/Masterminds/semver/v3 v3.1.1
> go: downloading github.com/imdario/mergo v0.3.11
> go: downloading github.com/google/uuid v1.1.1
> go: downloading github.com/spf13/cast v1.3.1
> go: downloading github.com/Masterminds/goutils v1.1.0
> go: downloading github.com/mitchellh/copystructure v1.0.0
> go: downloading github.com/shopspring/decimal v1.2.0
> go: downloading github.com/huandu/xstrings v1.3.1
> go: downloading github.com/mitchellh/reflectwalk v1.0.0
> go build github.com/benc-uk/k6-reporter: copying /tmp/go-build027705512/b001/exe/a.out: open bin/k6-reporter: permission denied
> **./scripts/build.sh: line 5: packr2: command not found**

$sudo ./scripts/build.sh

> ./scripts/build.sh: line 3: packr2: command not found
> ./scripts/build.sh: line 5: packr2: command not found

`

With the command "go run main.go", the k6-reporter application was created, but when I generate the report it is empty.

![resim](https://user-images.githubusercontent.com/3766764/108510202-45d02e00-72cf-11eb-9bda-bb3d98b13b5c.png)

**Comment by rodor87** [comment]
I believe I am getting a similar issue. I didn't get any errors while building the app, but the html report generated was empty

**Comment by giggio** [comment]
Same here, the tool runs but the report is empty.

**Comment by benc-uk** [comment]
Can you try with 1.2? which I just released, I don't remember but I may have fixed a few bugs
https://github.com/benc-uk/k6-reporter/releases/tag/1.2.0

**Comment by giggio** [comment]
@benc-uk it is still blank. I got the new params `infile` and `outfile`, but the result is still empty.
Please find attached the test file (json) and the generated result, I hope it helps.
[k6test.zip](https://github.com/benc-uk/k6-reporter/files/6142202/k6test.zip)

The test is a result from a simple test from k6:
```js
import { sleep } from 'k6';
import http from 'k6/http';

export default function () {
    http.get('http://test.k6.io');
    sleep(1);
}
```

Ran like this: `k6 run --vus 10 --out json=test.json --duration 30s script.js`

**Comment by giggio** [comment]
I just used the .js version, it works great. Nevermind the last comment.

**Comment by benc-uk** [comment]
Brilliant thanks
