### ISSUE TITLE
handleSummary doesn't work in combination with the standard textSummary output

### ISSUE THREAD

**Issue by Lamera** [benc-uk/k6-reporter#9]
I would like to get the html report and the standard output of k6 in one run.
The following snippet is my approach to get this running:
```
export function handleSummary(data) {
  console.log('Preparing the end-of-test summary...');
  return {
    'stdout': htmlReport(data),
    'stdout': textSummary(data, { indent: ' ', enableColors: true}),
  };
}
```
# Notes
I expect that this code generates an html report in the same directory, which doesn't happen.
I also tried to add the filename in the function, but still the same result.
`'stdout': htmlReport(data, { filename: "htmlreport.html" }),`

**Comment by benc-uk** [comment]
htmlReport returns the map that handle summary would normally return, where the keys refer to the filenames or stdout etc, this is so you can wrap it with minimum of code, eg. `return htmlReport(data)`

This does mean if you want to return your own object from handleSummary you need to intercept the result like this, and fetch the key (which is the filename) to get the raw string of the HTML

So to do what you require use this code

```js
export function handleSummary(data) {
  let html = htmlReport(data, { filename: `dummy` });
  return {
    "blah.html": html["dummy"],
    stdout: textSummary(data, { indent: " ", enableColors: true }),
  };
}
```

**Comment by benc-uk** [comment]
I've added this to the readme

**Comment by Lamera** [comment]
@benc-uk Thank you very much. This is exactly what I needed. Keep up the good work! 😄

**Comment by benc-uk** [comment]
Hi just letting you know I've changed this in v2.1.1 (also main) so that the htmlReport function just returns the HTML string
so the usage is now:
```js
export function handleSummary(data) {
  return {
    "summary.html": htmlReport(data),
  };
}
```
If you want the old behaviour you can carry on using the `2.0.0` tag
